### ISSUE TITLE
Add GraphQL Code Generator (codegen)

### ISSUE THREAD

**Issue by EnkhsaikhanCh** [EnkhsaikhanCh/nextjs-learn-acme#14]
## Summary
Add GraphQL Code Generator (codegen) to the project to automate the generation of type-safe code from GraphQL schemas and operations.

## Motivation
Using GraphQL Code Generator will help in generating type-safe code automatically, making the codebase more reliable and easier to maintain. It will also reduce the chances of runtime errors by providing compile-time type checking.

## Implementation Steps
1. **Install Dependencies:**
   - Install the necessary dependencies for GraphQL Code Generator.
     ```bash
     bun add @graphql-codegen/cli @graphql-codegen/typescript @graphql-codegen/typescript-operations @graphql-codegen/typescript-resolvers
     ```

2. **Create Codegen Configuration File:**
   - Create a `codegen.yml` file in the root directory with the following content:
     ```yaml
     schema: "http://localhost:3000/api/graphql"
     documents: "src/**/*.graphql"
     generates:
       src/generated/graphql.ts:
         plugins:
           - "typescript"
           - "typescript-operations"
           - "typescript-resolvers"
     ```

3. **Add Codegen Script to package.json:**
   - Add the codegen script to the `scripts` section of [package.json](http://_vscodecontentref_/0):
     ```json
     {
       "scripts": {
         "codegen": "graphql-codegen"
       }
     }
     ```

4. **Run Codegen Script:**
   - Run the codegen script to generate the type-safe code:
     ```bash
     bun run codegen
     ```

5. **Verify Generated Code:**
   - Verify that the generated code is correctly placed in the `src/generated/graphql.ts` file and is type-safe.

## Acceptance Criteria
- [x] GraphQL Code Generator dependencies are installed.
- [x] `codegen.yml` configuration file is created.
- [x] Codegen script is added to [package.json](http://_vscodecontentref_/1).
- [x] Codegen script runs successfully and generates type-safe code.
- [x] Generated code is verified and correctly placed in the project.

## Additional Context
- Refer to the [GraphQL Code Generator documentation](https://graphql-code-generator.com/docs/getting-started) for more details on configuration and usage.
